server:
  port: 7777
info:
  build:
    artifact: '@project.artifactId@'
    description: '@project.description@'
    groupId: '@project.groupId@'
    name: '@project.name@'
    version: '@project.version@'
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoeAnimation/config-repo
          username: JoeAnimation
          password: lyx484520
          basedir: F:\github\weixin-order\config\configuration
  rabbitmq:
    host: 192.168.1.12
    username: joe
    password: hadoop
    port: 5672
eureka:
  instance:
    hostname: localhost
  client:
    eureka-connection-idle-timeout-seconds: 3000
    eureka-server-port: 8761
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
